### ISSUE TITLE
 But when I click open in the menubar and select cancel in the dialog, it throws exception

### ISSUE THREAD

**Issue by igorgladkoborodov** [vv-vim/vv#16]
Uncaught Exception:
TypeError: Cannot read property 'length' of undefined
at O.o.dialog.showOpenDialog.e (/Applications/VV.app/Contents/Resources/app.asar/build/main.js:1:3805)
at Function.wrappedCallback (/Applications/VV.app/Contents/Resources/electron.asar/browser/api/dialog.js:130:57)

**Comment by igorgladkoborodov** [comment]
@ydzhou Fixed: https://github.com/vv-vim/vv/releases/tag/v1.5.2
